package pruebas;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

public class TestoneTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "..\\Testprime\\Driver\\chromedriver.exe");
	driver= new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testone() {
    driver.get("https://demoqa.com/automation-practice-form");
   // driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Jonathan");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("Rodriguez");
    driver.findElement(By.id("userEmail")).click();
    driver.findElement(By.id("userEmail")).sendKeys("jsteven@hotmaitl.com");
    driver.findElement(By.cssSelector(".custom-radio:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("userNumber")).click();
    driver.findElement(By.id("userNumber")).sendKeys("3121111111");
    js.executeScript("window.scrollTo(0,440)");
    driver.findElement(By.id("dateOfBirthInput")).click();
    /*driver.findElement(By.cssSelector(".react-datepicker__year-select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__year-select"));
      dropdown.findElement(By.xpath("//option[. = '2000']")).click();
    }

    driver.findElement(By.cssSelector(".react-datepicker__day--010")).click();
    js.executeScript("window.scrollTo(0,530)");
    driver.findElement(By.cssSelector(".subjects-auto-complete__value-container")).click();
    */
    
    //driver.findElement(By.id("react-select-2-option-0")).click();
   // driver.findElement(By.cssSelector(".custom-checkbox:nth-child(1) > .custom-control-label")).click();
    
    /*driver.findElement(By.id("uploadPicture")).click();
    driver.findElement(By.id("uploadPicture")).sendKeys("C:\\fakepath\\IMG_20211011_190306.jpg");
    */
    //driver.findElement(By.id("currentAddress")).click();
    driver.findElement(By.id("currentAddress")).sendKeys("cr 1");
    js.executeScript("window.scrollTo(0,930)");
    

  }
}
