package pruebas;

///Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestTest {
private WebDriver driver;

JavascriptExecutor js;
@Before
public void setUp() {
	
 //System.setProperty("webdriver.ie.driver", "..\\Testprime\\Driver\\IEDriverServer.exe");
 //driver= new InternetExplorerDriver();
 
 System.setProperty("webdriver.chrome.driver", "..\\Testprime\\Driver\\chromedriver.exe");
 driver= new ChromeDriver();
 //System.setProperty("webdriver.gecko.driver", "..\\Testprime\\Driver\\geckodriver.exe");
 //driver= new FirefoxDriver();
 js = (JavascriptExecutor) driver;
}
@After
public void tearDown() {
//try {
	 driver.quit();
//	}
//catch (Exception e) 
//   {}
}
@Test
public void Test() {
 driver.get("http://testfire.net/");
 driver.manage().window().setSize(new Dimension(697, 728));
 driver.findElement(By.cssSelector("font")).click();
 driver.findElement(By.cssSelector("#login tr:nth-child(1) > td:nth-child(2)")).click();
 driver.findElement(By.id("uid")).click();
 driver.findElement(By.id("uid")).sendKeys("jsmith");
 driver.findElement(By.id("login")).click();
 driver.findElement(By.id("passw")).click();
 driver.findElement(By.id("passw")).sendKeys("Demo1234");
 driver.findElement(By.name("btnSubmit")).click();
 driver.findElement(By.id("MenuHyperLink3")).click();
 driver.findElement(By.id("fromAccount")).click();
 {
   WebElement dropdown = driver.findElement(By.id("fromAccount"));
   dropdown.findElement(By.xpath("//option[. = '800003 Checking']")).click();
 }
 driver.findElement(By.id("toAccount")).click();
 {
   WebElement dropdown = driver.findElement(By.id("toAccount"));
   dropdown.findElement(By.xpath("//option[. = '4539082039396288 Credit Card']")).click();
 }
 driver.findElement(By.id("transferAmount")).click();
 driver.findElement(By.id("transferAmount")).sendKeys("7000");
 driver.findElement(By.id("transfer")).click();
 driver.findElement(By.cssSelector("tr:nth-child(6) > td")).click();
}
}
